'use client';

import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import Footer from './components/footer';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const currentpath = usePathname()
  return (
    <html lang="en">
      <body className={inter.className }>

       <div className='p-10 mt-1'>
        <Navbar/>
        {children}
        <ProgressBar/>
        <div>
         <Footer/>
        </div>
       </div>
      </body>
    </html>
  )
}
